name: Send telegram workflow
on:
  push:
    branches:
      - send_telegram_action
jobs:
  send_message:
    name: send_message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send message
        uses: ./actions/
        with:
          token_telegram: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_GROUP }}